<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Chef Paul Meals UG - Contact</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Chef Paul Meals UG" name="keywords">
        <meta content="Chef Paul Meals UG" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Playball&display=swap" rel="stylesheet">

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="lib/animate/animate.min.css" rel="stylesheet">
        <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">
        <link href="lib/owlcarousel/owl.carousel.min.css" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="css/style.css" rel="stylesheet">

        <!--form-->
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
            * {
              margin: 0;
              padding: 0;
              box-sizing: border-box;
            }
            body {
              font-family: "Inter", sans-serif;
            }
            .formbold-main-wrapper {
              display: flex;
              align-items: center;
              justify-content: center;
              padding: 48px;
            }
          
            .formbold-form-wrapper {
              margin: 0 auto;
              max-width: 550px;
              width: 100%;
              background: white;
            }
          
            .formbold-input-flex {
              display: flex;
              gap: 20px;
              margin-bottom: 15px;
            }
            .formbold-input-flex > div {
              width: 50%;
            }
          
            .formbold-input-radio-wrapper {
              margin-bottom: 28px;
            }
            .formbold-radio-flex {
              display: flex;
              align-items: center;
              gap: 15px;
            }
            .formbold-radio-label {
              font-size: 14px;
              line-height: 24px;
              color: #07074D;
              position: relative;
              padding-left: 25px;
              cursor: pointer;
              -webkit-user-select: none;
              -moz-user-select: none;
              -ms-user-select: none;
              user-select: none;
            }
            .formbold-input-radio {
              position: absolute;
              opacity: 0;
              cursor: pointer;
            }
            .formbold-radio-checkmark {
              position: absolute;
              top: -1px;
              left: 0;
              height: 18px;
              width: 18px;
              background-color: #FFFFFF;
              border: 1px solid #DDE3EC;
              border-radius: 50%;
            }
            .formbold-radio-label .formbold-input-radio:checked ~ .formbold-radio-checkmark {
              background-color: #6A64F1;
            }
            .formbold-radio-checkmark:after {
              content: "";
              position: absolute;
              display: none;
            }
          
            .formbold-radio-label .formbold-input-radio:checked ~ .formbold-radio-checkmark:after {
              display: block;
            }
          
            .formbold-radio-label .formbold-radio-checkmark:after {
              top: 50%;
              left: 50%;
              width: 10px;
              height: 10px;
              border-radius: 50%;
              background: #FFFFFF;
              transform: translate(-50%, -50%);
            }
          
            .formbold-form-input {
              width: 100%;
              padding: 13px 22px;
              border-radius: 5px;
              border: 1px solid #DDE3EC;
              background: #FFFFFF;
              font-weight: 500;
              font-size: 16px;
              color: #07074D;
              outline: none;
              resize: none;
            }
            .formbold-form-input::placeholder {
              color: #536387;
            }
            .formbold-form-input:focus {
              border-color: #6a64f1;
              box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
            }
            .formbold-form-label {
              color: #07074D;
              font-size: 14px;
              line-height: 24px;
              display: block;
              margin-bottom: 10px;
            }
          
            .formbold-btn {
              text-align: center;
              width: 100%;
              font-size: 16px;
              border-radius: 5px;
              padding: 14px 25px;
              border: none;
              font-weight: 500;
              background-color: #6A64F1;
              color: white;
              cursor: pointer;
              margin-top: 25px;
            }
            .formbold-btn:hover {
              box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
            }
          
          </style>
    </head>

    <body>

        


        <!-- Navbar start -->
        <div class="container-fluid nav-bar">
            <div class="container">
                <nav class="navbar navbar-light navbar-expand-lg py-4">
                    <a href="index.html" class="navbar-brand">
                        <h1 class="text-primary fw-bold mb-0">ChefPaul<span class="text-dark">Meals UG</span> </h1>
                    </a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a href="index.html" class="nav-item nav-link">Home</a>
                            <a href="about.html" class="nav-item nav-link">About</a>
                            <a href="service.html" class="nav-item nav-link">Services</a>
                           
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu bg-light">
                                    <a href="book.html" class="dropdown-item">Booking</a>
                                    <a href="blog.html" class="dropdown-item">Our Blog</a>
                                    <a href="team.html" class="dropdown-item">Our Team</a>
                                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                                    
                                </div>
                            </div>
                            <a href="contact.html" class="nav-item nav-link active">Contact</a>
                        </div>
                        
                        <a href="book.html" class="btn btn-primary py-2 px-4 d-none d-xl-inline-block rounded-pill">Book Now</a>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->


        


        


        <!-- Contact Start -->
        <div class="formbold-main-wrapper">
            
            <div class="formbold-form-wrapper">
              <form action="sendmail.php" method="POST">
                  <div class="formbold-input-flex">
                    <div>
                        <label for="firstname" class="formbold-form-label"> First name </label>
                        <input
                        type="text"
                        name="firstname"
                        id="firstname"
                        placeholder="Isaac"
                        class="formbold-form-input"
                        />
                    </div>
                    <div>
                        <label for="lastname" class="formbold-form-label"> Last name </label>
                        <input
                        type="text"
                        name="lastname"
                        id="lastname"
                        placeholder="Newton"
                        class="formbold-form-input"
                        />
                    </div>
                  </div>
          
                  <div class="formbold-input-flex">
                    <div>
                        <label for="email" class="formbold-form-label"> Mail </label>
                        <input
                        type="email"
                        name="email"
                        id="email"
                        placeholder="forexample@mail.com"
                        class="formbold-form-input"
                        />
                    </div>
                    <div>
                        <label for="phone" class="formbold-form-label"> Phone </label>
                        <input
                        type="text"
                        name="phone"
                        id="phone"
                        placeholder="(+265) 755501150"
                        class="formbold-form-input"
                        />
                    </div>
                  </div>
          
                  <div class="formbold-input-radio-wrapper">
                      <label for="jobtitle" class="formbold-form-label"> What are you looking for? </label>
          
                      <div class="formbold-radio-flex">
                        <div class="formbold-radio-group">
                          <label class="formbold-radio-label">
                            <input class="formbold-input-radio" type="radio" name="jobtitle" id="jobtitle">
                            Wedding Services
                            <span class="formbold-radio-checkmark"></span>
                          </label>
                        </div>
          
                        <div class="formbold-radio-group">
                          <label class="formbold-radio-label">
                            <input class="formbold-input-radio" type="radio" name="jobtitle" id="jobtitle">
                            Birthday Services
                            <span class="formbold-radio-checkmark"></span>
                          </label>
                        </div>
          
                        <div class="formbold-radio-group">
                          <label class="formbold-radio-label">
                            <input class="formbold-input-radio" type="radio" name="jobtitle" id="jobtitle">
                            Baby and Bridal Shower
                            <span class="formbold-radio-checkmark"></span>
                          </label>
                        </div>
          
                        <div class="formbold-radio-group">
                          <label class="formbold-radio-label">
                            <input class="formbold-input-radio" type="radio" name="jobtitle" id="jobtitle">
                            Others
                            <span class="formbold-radio-checkmark"></span>
                          </label>
                        </div>
                      </div>
                  </div>
          
                  <div>
                      <label for="message" class="formbold-form-label"> Message </label>
                      <textarea
                          rows="6"
                          name="message"
                          id="message"
                          placeholder="Type your message"
                          class="formbold-form-input"
                      ></textarea>
                  </div>
          
                  <button type="submit" class="formbold-btn">
                      Send Message
                  </button>
              </form>
            </div>
        </div>
          
        <!-- Contact End -->


        <!-- Footer Start -->
        <div class="container-fluid footer py-6 my-6 mb-0 bg-light wow bounceInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h1 class="text-primary">ChefPaul<span class="text-dark">Meals UG</span></h1>
                            <p class="lh-lg mb-4">The best catering services for Introduction/Wedding, Parties and all kinds of event.</p>
                            <div class="footer-icon d-flex">
                                <a class="btn btn-primary btn-sm-square me-2 rounded-circle" href="https://www.facebook.com/61568462535267"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-primary btn-sm-square me-2 rounded-circle" href="https://x.com/ChefUg99835"><i class="fab fa-twitter"></i></a>
                                <a href="https://www.instagram.com/chefpaulmeals?igsh=Z2Ixa21zeTk4Nmhv" class="btn btn-primary btn-sm-square me-2 rounded-circle"><i class="fab fa-instagram"></i></a>
                                <a href="http://tiktok.com/@chefpaulug1" class="btn btn-primary btn-sm-square rounded-circle"><i class="fab fa-tiktok"></i></a>
                                <a href="https://youtube.com/@chefpaulmealsug?si=yqurP7lJunP5wRJt" class="btn btn-primary btn-sm-square rounded-circle"><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="mb-4">Special Facilities</h4>
                            <div class="d-flex flex-column align-items-start">
                                <a class="text-body mb-3" href=""><i class="fa fa-check text-primary me-2"></i>Food/meals</a>
                                <a class="text-body mb-3" href=""><i class="fa fa-check text-primary me-2"></i>Cakes</a>
                                <a class="text-body mb-3" href=""><i class="fa fa-check text-primary me-2"></i>Outside Catering services</a>
                                <a class="text-body mb-3" href=""><i class="fa fa-check text-primary me-2"></i>Special Foods</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="mb-4">Contact Us</h4>
                            <div class="d-flex flex-column align-items-start">
                                <p><i class="fa fa-map-marker-alt text-primary me-2"></i> Martyrs Mall ,Kira Road, Kyalwajala, Uganda</p>
                                <p><i class="fa fa-phone-alt text-primary me-2"></i> (+256) 751216909</p>
                                <p><i class="fas fa-envelope text-primary me-2"></i> chefpaulug@gmail.com</p>
                                <p><i class="fa fa-clock text-primary me-2"></i> 24/7 Hours Service</p>
                                <p><a href="https://wa.me/+256751216909?text=Hello,%20I%20want%20to%20learn%20more!">Click to contact me on WhatsApp</a></p>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Copyright Start -->
        <div class="container-fluid copyright bg-dark py-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>Chef Paul Meals UG</a>, All right reserved.</span>
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- Copyright End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-md-square btn-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/lightbox/js/lightbox.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
    </body>

</html>